# Generated by Django 4.2.2 on 2023-06-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('seling_price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('description', models.TextField()),
                ('composition', models.TextField(default='')),
                ('prodapp', models.TextField(default='')),
                ('category', models.CharField(choices=[('Sm', 'Sumgsung'), ('Op', 'Oppo'), ('Xi', 'Xiaomi'), ('Re', 'Realme')], max_length=2)),
                ('Product_img', models.ImageField(upload_to='products')),
            ],
        ),
    ]
