# Generated by Django 4.2.2 on 2023-06-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Sm', 'Sumgsung'), ('Op', 'Oppo'), ('Xi', 'Xiaomi'), ('Re', 'Realme'), ('One', 'OnePlus'), ('Vi', 'Vivo')], max_length=3),
        ),
    ]
